### ISSUE TITLE
Error: Unable to fetch data.

### ISSUE THREAD

**Issue by nxfxcom** [jakecreps/poastal#21]
Hello,

I followed the instructions to the letter ;) Below is the console output:

`127.0.0.1 - - [27/Feb/2024 10:03:12] "GET /?email=test@gmail.com HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Volumes/WORK/APPS/poastal/backend/poastal.py", line 34, in poastal
    rumble_result = rumble_email(email)
  File "/Volumes/WORK/APPS/poastal/backend/modules/rumble.py", line 18, in rumble_email
    response = requests.post('https://rumble.com/register.php', params=params, headers=headers, data=data)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/nxfxcom/anaconda3/envs/py3_knime/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Thank you

**Comment by PAICyclops** [comment]
Yes, I had the same issue and can't resolve it.  
The problem seems to occur within the urllib3 library.  However, I found a workarround to comment out the rumble_result module in cli.py.  I commented the github modules as well, since I didn't use a github token; so I'm not sure if there occurs an error as well.
![image](https://github.com/jakecreps/poastal/assets/67309841/090ef6fe-e527-4be4-8a21-edcccb8140d2)
