### ISSUE TITLE
ModuleNotFoundError: No module named 'twitter'

### ISSUE THREAD

**Issue by tomtom1337** [jakecreps/poastal#6]
Hi and thanks for the great work!

I've got an issue with loading the local twitter module from the modules folder:
```
Traceback (most recent call last):
  File "poastal.py", line 7, in <module>
    from twitter import twitter_email
ModuleNotFoundError: No module named 'twitter'
```

Workaround for me was to add the modules folder to the import command in the `poastal.py`
```
#import modules
from modules.twitter import twitter_email
```

And now it's working :)

**Comment by chanoir2303** [comment]
Recommendation is to install your dependencies into a virtual environment

**Comment by tomtom1337** [comment]
> Recommendation is to install your dependencies into a virtual environment

This does not solve my issue... still ``` No module named 'twitter' ```. 
The only solution is to add ```modules.``` to load the local modules correctly

**Comment by chanoir2303** [comment]
Can you reproduce how did you install the project requirements for us?

**Comment by jakecreps** [comment]
Did you change any folder names?

sys.path.append(os.path.abspath('./modules'))

This should import the location of all of the modules into the script.

**Comment by tomtom1337** [comment]
I've tried it on a fresh installation of Linux Mint 21.1 in Virtual Box:

```bash
v@v-VirtualBox:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera
v@v-VirtualBox:~$ python3 --version
Python 3.10.6
```

Installation:
```bash
@v-VirtualBox:~$ git clone https://github.com/jakecreps/poastal
Klone nach 'poastal' …
remote: Enumerating objects: 178, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 178 (delta 29), reused 0 (delta 0), pack-reused 101
Empfange Objekte: 100% (178/178), 150.11 KiB | 3.00 MiB/s, fertig.
Löse Unterschiede auf: 100% (65/65), fertig.
v@v-VirtualBox:~$ cd poastal/
v@v-VirtualBox:~/poastal$ pip install -r requirements.txt
[ ... ]
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.2 Werkzeug-2.2.3 flask-2.2.3 flask_cors-3.0.10 itsdangerous-2.1.2
v@v-VirtualBox:~/poastal$ python3 backend/poastal.py 
Traceback (most recent call last):
  File "/home/v/poastal/backend/poastal.py", line 7, in <module>
    from twitter import twitter_email
ModuleNotFoundError: No module named 'twitter'
```

I've added `print(sys.path)` to check if the `sys.path.append` is working:

```bash
['/home/v/poastal/backend', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/v/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages', '/home/v/poastal/modules']
```

Only solution is to load all the local modules with 
`from modules.xxx import xxx`

**Comment by tomtom1337** [comment]
So the problem is that if you don't run `poastal.py` from the `backend` folder itself it throws the `ModuleNotFoundError` because it looks for `.../poastal/modules` instead of `.../poastal/backend/modules`

So you may close this issue or you can add my workaround `modules.xxxx` to run `poastal.py` from anywhere 😄
